src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'entity.user.validators.email_validation')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(length: 180, unique: true)]
    private string $email;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    #[ORM\Column]
    private bool $isVerified = false;

    /**
     * @var Collection<int, MovieWatchlist>
     */
    #[ORM\OneToMany(targetEntity: MovieWatchlist::class, mappedBy: 'owner', orphanRemoval: true)]
    private Collection $movieWatchlists;

    public function __construct()
    {
        $this->movieWatchlists = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @return list<string>
     *
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, MovieWatchlist>
     */
    public function getMovieWatchlists(): Collection
    {
        return $this->movieWatchlists;
    }

    public function addMovieWatchlist(MovieWatchlist $movieWatchlist): static
    {
        if (!$this->movieWatchlists->contains($movieWatchlist)) {
            $this->movieWatchlists->add($movieWatchlist);
            $movieWatchlist->setOwner($this);
        }

        return $this;
    }

    public function removeMovieWatchlist(MovieWatchlist $movieWatchlist): static
    {
        $this->movieWatchlists->removeElement($movieWatchlist);

        return $this;
    }

    /**
     * @param iterable<MovieWatchlist> $watchlists
     */
    public function ownsWatchlists(iterable $watchlists): bool
    {
        foreach ($watchlists as $watchlist) {
            if (!$watchlist->hasOwner($this)) {
                return false;
            }
        }

        return true;
    }

    public function __toString(): string
    {
        return $this->email;
    }
}

src/Controller/Frontend/ProfileController.php
<?php

declare(strict_types=1);

namespace App\Controller\Frontend;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

class ProfileController extends AbstractController
{
    #[Route('/{_locale}/profile', name: 'app_profile_index')]
    public function index(#[CurrentUser] User $user): Response
    {
        return $this->render('profile/index.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/profile/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 text-center">
                <i class="bi bi-person-circle" style="font-size: 5rem"></i>
                <h3>{{ 'templates.profile.sections.profile_information'|trans }}</h3>
                <ul class="list-group mb-3 text-start">
                    <li class="list-group-item">
                        <div class="d-flex flex-column">
                            <div>
                                <strong>{{ 'templates.profile.fields.email'|trans }}</strong>
                            </div>
                            <div class="row">
                                <div class="text-truncate col">
                                    <span data-bs-toggle="tooltip" data-bs-placement="top"
                                          data-bs-title="{{ user.email }}">
                                        {{ user.email }}
                                    </span>
                                </div>
                                <div class="col-auto">
                                    {% if user.verified %}
                                        <i class="bi bi-shield-fill-check text-success"
                                           data-bs-toggle="tooltip" data-bs-placement="top"
                                           data-bs-title="{{ 'templates.profile.tooltips.email_verified'|trans }}"></i>
                                    {% else %}
                                        <i class="bi bi-shield-slash-fill text-danger"
                                           data-bs-toggle="tooltip" data-bs-placement="top"
                                           data-bs-title="{{ 'templates.profile.tooltips.email_not_verified'|trans }}"></i>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex flex-column">
                            <div>
                                <strong>{{ 'templates.profile.fields.roles'|trans }}</strong>
                            </div>
                            <div>
                                {% for role in user.roles %}
                                    <span class="badge bg-{{ role|roleStyle }}">{{ role|roleTransKey|trans }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-md-8">
                <h3>{{ 'templates.profile.sections.your_watchlists'|trans }}</h3>
                <div class="list-group">
                    {% for watchlist in user.movieWatchlists %}
                        <a class="list-group-item list-group-item-action"
                           href="{{ path('app_movie_watchlists_show', {id: watchlist.id}) }}">
                            {{ watchlist.name }}
                        </a>
                    {% endfor %}
                    {% if user.movieWatchlists.empty %}
                        <h4 class="text-center text-danger bg-opacity-75 bg-body-secondary p-2 rounded">
                            <i class="bi bi-emoji-frown-fill"></i> {{ 'templates.profile.other.no_watchlist_found'|trans }}
                        </h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}